const todayWeatherApi: TodayWeatherT = {
  queryCost: 1,
  latitude: 39.9066,
  longitude: 116.388,
  resolvedAddress: "中国北京",
  address: "BeiJing, China",
  timezone: "Asia/Shanghai",
  tzoffset: 8,
  days: [
    {
      datetime: "2024-02-25",
      datetimeEpoch: 1708790400,
      tempmax: 9,
      tempmin: -6,
      temp: 2,
      feelslikemax: 7.3,
      feelslikemin: -9.6,
      feelslike: -0.6,
      dew: -12.8,
      humidity: 38.3,
      precip: 0,
      precipprob: 0,
      precipcover: 0,
      preciptype: null,
      snow: 0,
      snowdepth: 0.1,
      windgust: 27,
      windspeed: 12.6,
      winddir: 351.6,
      pressure: 1030.9,
      cloudcover: 10.1,
      visibility: 14.7,
      solarradiation: 192.1,
      solarenergy: 16.6,
      uvindex: 7,
      severerisk: 10,
      sunrise: "06:54:58",
      sunriseEpoch: 1708815298,
      sunset: "18:00:57",
      sunsetEpoch: 1708855257,
      moonphase: 0.52,
      conditions: "Clear",
      description: "Clear conditions throughout the day.",
      icon: "clear-day",
      stations: ["ZBAA", "remote"],
      source: "comb",
    },
  ],
  stations: {
    ZBAA: {
      distance: 24475,
      latitude: 40.07,
      longitude: 116.58,
      useCount: 0,
      id: "ZBAA",
      name: "ZBAA",
      quality: 50,
      contribution: 0,
    },
  },
};

export default todayWeatherApi;
